# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30ea40ecdb2e4712495e3d70ba8b92b0ed76428b75dbc058388281f6f3f5f3cb18b862d806ca8887f4fd3049d54653d49b7e857e517934052aa107b5d01f44bc

test:
  secret_key_base: aabac46a6179132c3bd699288a78cc459c6543cb2b56b2a893cc388b7ce0ce11e03483ae446520b06feaefc8ec3a37f780e6ee3d7064bee6e0216a3fac32d28d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
